# this is an official Python runtime, used as the parent image
FROM python:3.6.5-slim

# set the working directory in the container to /app
WORKDIR /usr/src/api

# execute everyone's favorite pip command, pip install -r
RUN pip install bs4
RUN pip install flask
RUN pip install requests
RUN pip install pymongo
